### ISSUE TITLE
Ability to List albums? 

### ISSUE THREAD

**Issue by jspenc72** [esteban-uo/picasa#2]
Does this library support ability to List a user's albums?

**Comment by esteban-uo** [comment]
hi @jspenc72, it didn't, but now it does. It was a quick implementation and was published under the v1.0.2 tag. Check under examples the getAlbums.js file.

It is not mapping all albums fields, but maybe it is enough for now. Let me know if it helps you, otherwise I will update it soon. 

Greetings!

**Comment by jspenc72** [comment]
If you can make so we can access any metadata for the albums that would be amazing.

**Comment by jspenc72** [comment]
Metadata ***

**Comment by jspenc72** [comment]
And yes, it helps a lot! Thank you for adding this!

**Comment by esteban-uo** [comment]
@jspenc72 I'll close this issue and open a new one in order to show any metadata for the albums
